'use client';

import { useEffect, useState } from 'react';
import { CopyButton } from './copy-button';

/**
 * QR display and download.
 *
 * The SVG is fetched from the server (which owns the encoder) rather than
 * shipping the encoder to the browser. PNG download is produced client-side by
 * rasterising that SVG onto a canvas, so no second round trip is needed.
 */

export function QrPanel({ value, filename }: { value: string; filename: string }) {
  /**
   * Result state is keyed by the value it belongs to, so a change of `value`
   * invalidates the previous result during render rather than through a
   * setState call inside the effect (which would cause a cascading render).
   */
  const [result, setResult] = useState<{ value: string; svg: string | null; failed: boolean }>({
    value,
    svg: null,
    failed: false,
  });

  const current = result.value === value ? result : { value, svg: null, failed: false };
  const svg = current.svg;
  const error = current.failed;

  useEffect(() => {
    let cancelled = false;

    fetch(`/api/qr?content=${encodeURIComponent(value)}`)
      .then((response) => {
        if (!response.ok) throw new Error('QR request failed');
        return response.text();
      })
      .then((text) => {
        if (!cancelled) setResult({ value, svg: text, failed: false });
      })
      .catch(() => {
        if (!cancelled) setResult({ value, svg: null, failed: true });
      });

    return () => {
      cancelled = true;
    };
  }, [value]);

  async function downloadPng() {
    if (!svg) return;
    const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    try {
      const image = new Image();
      image.decoding = 'sync';
      await new Promise<void>((resolve, reject) => {
        image.onload = () => resolve();
        image.onerror = () => reject(new Error('Could not load QR image'));
        image.src = url;
      });

      const size = 1024;
      const canvas = document.createElement('canvas');
      canvas.width = size;
      canvas.height = size;
      const context = canvas.getContext('2d');
      if (!context) return;

      context.imageSmoothingEnabled = false;
      context.fillStyle = '#FFFFFF';
      context.fillRect(0, 0, size, size);
      context.drawImage(image, 0, 0, size, size);

      const link = document.createElement('a');
      link.download = `zurl-${filename}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } finally {
      URL.revokeObjectURL(url);
    }
  }

  function downloadSvg() {
    if (!svg) return;
    const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = `zurl-${filename}.svg`;
    link.href = url;
    link.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="flex flex-col items-start gap-4 sm:flex-row sm:items-center">
      <div className="shrink-0 rounded-lg bg-white p-2.5">
        {svg ? (
          <div
            className="h-32 w-32 [&>svg]:h-full [&>svg]:w-full"
            // The SVG is generated by our own server-side encoder from a
            // validated URL; it contains no script and no user-controlled
            // markup — only <rect> and <path> geometry.
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : (
          <div className="flex h-32 w-32 items-center justify-center text-xs text-faint">
            {error ? 'Unavailable' : 'Generating…'}
          </div>
        )}
      </div>

      <div className="min-w-0 flex-1">
        <p className="text-sm font-medium text-ink">Scan to open this link</p>
        <p className="mt-0.5 font-mono text-xs break-all text-subtle">{value}</p>

        <div className="mt-3 flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={downloadPng}
            disabled={!svg}
            className="inline-flex h-9 items-center rounded-md bg-surface-raised px-3 text-sm font-medium text-ink transition-colors hover:bg-surface-hover disabled:opacity-50"
          >
            Download PNG
          </button>
          <button
            type="button"
            onClick={downloadSvg}
            disabled={!svg}
            className="inline-flex h-9 items-center rounded-md px-3 text-sm font-medium text-muted transition-colors hover:bg-surface-raised hover:text-ink disabled:opacity-50"
          >
            SVG
          </button>
          <CopyButton value={value} label="Copy link" variant="ghost" />
        </div>
      </div>
    </div>
  );
}
